# .github/workflows/deploy-gcloud.yml

name: Deploy API to Google Cloud
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  #PROJECT_ID: ${{ secrets.GCP_PROJECT_ID2 }}
  #APP_ID: devopsudem
  APP_ID: autosudem
  #RUN_REGION: us-east1
  #SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
  #SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON2 }}
jobs:
  deploy:
    name: Deploy DevOpsAPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with: 
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}
          #credentials_json: ${{ secrets.GCP_SA_KEY_JSON2 }}
  
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 363.0.0"
          

      # Build and push image to Google Container Registry
      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA

      #- name: Deploy
       # run: gcloud run deploy $APP_ID --image gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.5.7

      - name: Terraform init and validate
        run: |
          terraform init

      - name: Terraform plan
        run: |
          terraform plan

      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: Santiagop212
          minimum-approvals: 1
          issue-title: "Deploying with Terraform to GCP"
          issue-body: "Review the terraform plan, then approve or deny the deployment to GCP."
          exclude-workflow-initiator-as-approver: false

      - name: Terraform apply
        run: |
          terraform apply -auto-approve    
