name: Terraform Apply

on:
  pull_request_review:
    types: [submitted]

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Terraform Apply
        run: terraform apply -auto-approve
      - name: Post comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ inputs.github_token }}
          issue-number: ${{ inputs.pr_id }}