name: Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Terraform Plan
        run: terraform plan -no-color
      - name: Post comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ inputs.github_token }}
          issue-number: ${{ inputs.pr_id }}
          body: |
            Terraform Plan:
            ```
            ${{ steps.plan.outputs.plan }}
            ```